package app.stockpickers.kmp.data.remote

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.decodeFromJsonElement

/**
 * One row of `descriptions_cache` — the pipeline's written profile for a ticker.
 *
 * The two blocks are separate JSONB columns upstream, generated by different steps
 * and carrying their own timestamps and TTLs. Both are routinely `{}` (the row was
 * created before its text was), and both can be SQL NULL, hence nullable properties
 * over classes whose every member already defaults to null.
 *
 * Nothing here depends on the shared `Json` being lenient: every field is nullable
 * with a default, so an empty object, a missing key, or a null decodes cleanly under
 * any configuration. A field whose TYPE is wrong is a different matter and is left to
 * throw — that is a breaking upstream change, and it should fail loudly (one row
 * dropped, card absent) rather than be papered over field by field.
 */
@Serializable
data class DescriptionsRowDto(
    val ticker: String,
    val timeless: DescriptionBlockDto? = null,
    val current: DescriptionBlockDto? = null,
)

/**
 * A block of generated text plus its own freshness metadata.
 *
 * `ttl_days` is deliberately NOT defaulted to upstream's 30/7 here: those are domain
 * policy and belong in the mapper, so this stays a faithful description of the wire
 * format and nothing more.
 */
@Serializable
data class DescriptionBlockDto(
    val description: String? = null,
    /** Present on the `current` block only. */
    val pro: List<String>? = null,
    val con: List<String>? = null,
    /**
     * **Polymorphic upstream** — held as raw JSON and narrowed by [nextEarningsOrNull].
     *
     * Some rows carry an object (`{date, consensus, days_away}`), others a bare string
     * of prose ("Q2 2026 consolidated results expected around August 2026 …"). Measured
     * over the live table: 85 objects, 63 strings, 151 absent, out of 299 rows. Typed
     * as either concrete shape, **43% of the rows that have earnings at all** fail to
     * decode — and since a field error kills the whole row, their entire profile
     * silently disappears. That is exactly the bug this replaced.
     */
    @SerialName("next_earnings") val nextEarnings: JsonElement? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("ttl_days") val ttlDays: Int? = null,
)

/**
 * Narrows the polymorphic `next_earnings` to one shape.
 *
 * The bare-string form is prose about the next report, which is the same role
 * [NextEarningsDto.consensus] plays in the object form — so it maps there, and the
 * rest of the app sees a single shape. Anything unrecognisable yields null rather than
 * throwing: one odd field must not cost the reader the whole profile.
 */
fun DescriptionBlockDto.nextEarningsOrNull(json: Json): NextEarningsDto? = when (val element = nextEarnings) {
    null, JsonNull -> null

    is JsonObject -> runCatching { json.decodeFromJsonElement<NextEarningsDto>(element) }.getOrNull()

    is JsonPrimitive -> element.takeIf { it.isString }?.content
        ?.takeIf { it.isNotBlank() }
        ?.let { NextEarningsDto(consensus = it) }

    else -> null
}

@Serializable
data class NextEarningsDto(
    val date: String? = null,
    val consensus: String? = null,
    /**
     * Double, NOT Int, on purpose: this is written by a pandas/numpy pipeline, which
     * emits `12.0` as readily as `12`. Typing it as Int would make one such row fail
     * to decode and take the whole profile down with it. Rounded in the mapper.
     */
    @SerialName("days_away") val daysAway: Double? = null,
)
